Feature: Teacher creates quiz with 3 Textual Questions, 3 Single Choice Qyestions, and 3 Multiple Choice Questions.
  @EndtoEnd
  Scenario:Login to Teacher's Account
    Given Navigate to web page (URL)
    When URL is "http://www.local.portnov.com:4520/api/v1/login"
    And I type email: "eami@lkoqmcvtjbq.gq"
    Then I type password "12345"
    Then I push "Sign In"
    Then I click on "Quizzes" in the left navigation panel
    Then I click on "Create New Quizzes"
    Then I click "Submit" button
    Then I verify URL is "http://www.local.portnov.com:4520/api/v1/quiz-builder"
    Then I write the Quiz Title as "Mathematics: Arithmetic"
    Then I click "Add Question"
    Then I choose "Type of Question" as "Textual"
    Then I typed in "Question*" Record "What is 2 x 2?"
    Then I click on "Add Question"
    Then I choose "Type of Question" as "Textual"
    Then I typed in "Question*" Record "What s 3 x 3?"
    Then I click "Add Question"
    Then I choose "Type of Question" as "Textual"
    Then I typed in "Question*" Record "What is 4 x 4?"
    Then I click on "Add Question"
    Then I choose "Type of Question" as "Single Choice"
    Then I type in "Questions*" Record " What is "2 + 4"?
    Then I click "Add Question"
    Then I choose "Type of Question" as "Single Choice"
    Then I type in "Questions*" Record "What is 2+6"?
    Then I click "Add Question"
    Then I choose "Type of Question" as "Single Choice"
    Then I type in "Questions*" Record "What is 2+8?"
    Then I click "Add Question"
    Then I choose "Type of Question" as "Multiple Choice Question"
    Then I type in "Questions*" Record "What is 2 + 10?"
    Then I select answers for A. "2"
    Then I select answers for B. "4"
    Then I select answers for C. "6"
    Then I select answers for D. "12"
    Then I click "Add Question"
    Then I choose "Type of Question" as Multiple Choice Question"
    Then I type in "Questions*" Record "What is "2+12?"
    Then I select answers for A. "6"
    Then I select answers for B. "8"
    Then I select answers for C. "10"
    Then I select answers for D. "14"
    Then I choose "Type of Question" as "Multiple Choice Question"
    Then I type in "Questions*" Record "What is 2+14?"
    Then I select answers for A. "10"
    Then I select answers for B. "12"
    Then I select answers for C. "14"
    Then I select answers for D. "16"
