Feature:Teacher assigns Quiz to a single student. Student completes Quiz and it automatically graded as Passed. Teacher reviews the assignment and deletes it. The grade is also deleted from students board
  Scenario:Alphanumerical&Spchar
    When Navigate to registration page "http://local.school.portnov.com:4520/#/registration"
    Then Login as a Teacher with Email"olenqa12@yandex.com"  xpath"//input[@placeholder='Email *']" and "Password" "12345"and password xpath "//input[@placeholder='Password *']"
    And click on "Sign in" with x-path"//span[contains(text(),'Sign In')]"
    Then Click on the "Assignments"with thw xpath"// *[text()='Assignments']"
    And Push "Create New Assignment" button with the xpath"//span[contains(text(),'Create New Assignment')]"
    And Click on triangle on the "Group Filter" drop-down list with xpath "//mat-select[@id='mat-select-2']//div[@class='mat-select-arrow-wrapper']"
    Then Click on the "Students" list checkbox "Elena Barmalley" with xpath "//mat-selection-list[@class='mat-selection-list ng-dirty ng-valid ng-touched']//mat-list-option[29]//div[1]//div[2]"
    And Push "Select Quiz To Assign" tab with xpath"//span[contains(text(), 'Select Quiz To Assign')]"
    And Push "Select Quiz To Assign" list-option to select the quiz"Q2" with xpath "//*[contains(text(),'Q2')]"
    And Push button"Give Assignment" with xpath "//span[contains(text(),'Give Assignment')]"
    Then Push the "Log Out" button on the left navigation panel with xpath "//h5[contains(text(),'Log Out')]"
    And Click on the confirmation logout window with xpath"//span[contains(text(),'Log Out')]"
    And Login as a student with Email "paym@email2an.ga" xpath "
  //input[@placeholder='Email *']" and "Password" "12345"and password xpath "//input[@placeholder='Password *']"
    Then Click on "My Assignments" on the left navigation panel with xpath "//h5[contains(text(),'My Assignments')]"
    And Click on "Go to Assignment" button with xpath "//*[contains(text(), 'history')]/..//*[contains(text(), 'Go To Assessment')]"
    And Push button with right answer "a" with xpath "//mat-radio-button[@id='mat-radio-13']//div[@class='mat-radio-inner-circle']"
    And Push "Submit My Answers" button with xpath "//span[@class='mat-button-wrapper']"
    And Push "Ok" button in the popped-up confirmation window with xpath "//span[contains(text(),'Ok')]"
    Then Click on "My Grades" on the left navigation panel with xpath"//h5[contains(text(),'My Grades')]"
    And Push "Log Out" button at the left bottom of Main Menu with xpath "//h5[contains(text(),'Log Out')]"
    And Push "Log Out" button in the Confirmation window with xpath "//span[contains(text(),'Log Out')]"
    Then Login as the Teacher with Email"olenqa12@yandex.com"  xpath"//input[@placeholder='Email *']" and "Password" "12345"and password xpath "//input[@placeholder='Password *']"
    And Click on "Sign in" with x-path"//span[contains(text(),'Sign In')]"
    And Click on "Submissions" on the left navigation panel with xpath"//h5[contains(text(),'Submissions')]"
    And Click on "Automatically Graded" tab with xpath "//div[contains(text(),'Automatically Graded')]"
    Then Push "Review" button with xpath"//a[@href='/#/grade/15526?back=submissions/1']//button[@class='mat-raised-button mat-primary']"
    And Click "Assigments" on left navigation panel on left navigation panel with xpath "//h5[contains(text(),'Assignments')]"
    And Click burger menu with xpath"//mat-panel-title[@class='mat-expansion-panel-header-title'][contains(text(),' Quiz:   history')]"
    Then Push "Delete button" with xpath"//span[contains(text(),'Delete Assignment')]"
    And Click "Delete" button on a confirmation window with xpath "//span[contains(text(),'Delete')]"
    And Push "Log Out" button at the left bottom of Main Menu with xpath"//h5[contains(text(),'Log Out')]"
    And Push "Log Out" button in the Confirmation windowwith xpath"//span[contains(text(),'Log Out')]"
    Then Login as a student with Email "paym@email2an.ga" xpath "
  //input[@placeholder='Email *']" and "Password" "12345"and password xpath "//input[@placeholder='Password *']"
    And Click on "My Grades" on the left navigation panel with xpath"//h5[contains(text(),'My Grades')]"
    Then Click on "Go to my grades" button with xpath "//span[contains(text(),'Go To My Grades')]"